services:
  webvue:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:3333}
      - VITE_WITH_CREDENTIALS=${VITE_WITH_CREDENTIALS:-false}
      - VITE_AUTH_LOGIN=${VITE_AUTH_LOGIN:-/auth/login}
      - VITE_AUTH_REFRESH=${VITE_AUTH_REFRESH:-/auth/refresh}
      - VITE_AUTH_LOGOUT=${VITE_AUTH_LOGOUT:-/auth/logout}
      - USE_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - POLLING_INTERVAL=300
      - VITE_DEV_PORT=5173
